"use client";

import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
} from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 12,
    fontFamily: "Helvetica",
    lineHeight: 1.5,
  },
  header: {
    fontSize: 24,
    fontWeight: "bold",
    marginBottom: 20,
    color: "#b48a2a",
  },
  subHeader: {
    fontSize: 14,
    marginBottom: 20,
    color: "#333",
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
    paddingVertical: 8,
  },
  label: {
    fontWeight: "bold",
    color: "#555",
  },
  value: {
    color: "#000",
  },
  footer: {
    marginTop: 40,
    fontSize: 10,
    color: "#777",
    textAlign: "center",
  },
  stamp: {
    marginTop: 30,
    padding: 10,
    borderWidth: 2,
    borderColor: "#2d6a4f",
    borderStyle: "dashed",
    alignSelf: "flex-start",
    color: "#2d6a4f",
    fontWeight: "bold",
  },
});

export function ReceiptDocument({
  tenantName,
  roomNumber,
  amount,
  method,
  paidAt,
  reference,
  title = "Rent Payment Receipt",
  apartmentName = "PK Luxury Apartments",
  apartmentLocation = "Haatso, Ghana",
}: {
  tenantName: string;
  roomNumber: string;
  amount: string;
  method: string;
  paidAt: string;
  reference: string;
  title?: string;
  apartmentName?: string;
  apartmentLocation?: string;
}) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.header}>{apartmentName}</Text>
        <Text style={styles.subHeader}>{title}</Text>

        <View style={styles.row}>
          <Text style={styles.label}>Tenant</Text>
          <Text style={styles.value}>{tenantName}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Room Number</Text>
          <Text style={styles.value}>{roomNumber}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Amount Paid</Text>
          <Text style={styles.value}>{amount}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Payment Method</Text>
          <Text style={styles.value}>{method}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Payment Date</Text>
          <Text style={styles.value}>{paidAt}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Reference</Text>
          <Text style={styles.value}>{reference}</Text>
        </View>

        <View style={styles.stamp}>
          <Text>PAYMENT CONFIRMED</Text>
        </View>

        <Text style={styles.footer}>
          {apartmentName} • {apartmentLocation}
Generated by PK Apartments Management System
        </Text>
      </Page>
    </Document>
  );
}
